export const workList = [
  {
    id: 1,
    title: "Khwanta Handicraft Website",
    description:
      "Design and develop a web applications with a focus on optimal SEO using Next.js.Implementing responsive design, ensuring a seamless user experience across various devices",
    category: "Full stack development",
    year: "2021",
    client: "Khwanta Handicraft",
    blackground: "bg-yellow-500",
    frameWork: ["Next.js", "MongoDB", "TailwindCSS"],
    image: "/work/khwantawebsite.png",
  },
  {
    id: 2,
    title: "Khwanta Handicraft Admin Dashboard",
    description:
      "Designing and deploying a admin dashboard to streamline stock management processes.The admin dashboard is equipped to handle intricate tasks such as maintaining detailed product information with variant sizes and colors, proficient stock management, syncing sales data seamlessly from POS systems across multiple branches, and managing customer information. ",
    category: "Full stack development",
    year: "2021",
    client: "Khwanta Handicraft",
    blackground: "bg-yellow-500",
    frameWork: ["React", "MongoDB", "TailwindCSS", "Express.js", "Node.js"],
    image: "/public/work/khwantaDashboard.png",
  },
  {
    id: 3,
    title: "Khwanta Handicraft Pos System",
    description:
      "Designing and implementing a comprehensive POS system utilizing Electron.js, React.js, and Node.js, with MongoDB as the database backend.Pos system can sync data back to the stock management program, and it can also sync data to the cloud for the admin dashboard.My focus includes developing an intuitively designed user interface for effortless usability, ensuring compatibility for all users.",
    category: "Full stack development",
    year: "2021",
    client: "Khwanta Handicraft",
    blackground: "bg-yellow-500",
    frameWork: ["React", "MongoDB", "TailwindCSS", "Electron.js", "Express.js"],
    image: "/work/posSystem.jpg",
  },
  {
    id: 4,
    title: "Khwanta Handicraft Stock Management Program",
    description:
      "Designing and implementing a comprehensive stock management program utilizing Electron.js, React.js, express.js, and MongoDB. The program is designed to be user-friendly and efficient.The program encompasses stock management functionality with cloud synchronization, facilitating seamless stock transfers from the management system to the POS (Point of Sale) system through the cloud, along with reporting capabilities to admin dashboard.",
    category: "Full stack development",
    year: "2022",
    client: "Khwanta Handicraft",
    blackground: "bg-yellow-500",
    frameWork: ["React", "MongoDB", "TailwindCSS", "Electron.js", "Express.js"],
    image: "/work/Warehouse.jpg",
  },
  // {
  //   id: 5,
  //   title: "E-learning Platform",
  //   description:
  //     "Developing an E-learning platform tailored for students to easily purchase courses, monitor their progress, and for teachers to effortlessly upload new courses and manage course details. Our platform prioritizes user-friendliness and efficiency, ensuring a seamless experience for both students and educators.",
  //   category: "Full stack development",
  //   year: "2024",
  //   client: "Personal Project",
  //   blackground: "bg-yellow-500",
  //   frameWork: [
  //     "Next.js",
  //     "Prisma",
  //     "TailwindCSS",
  //     "Electron.js",
  //     "Express.js",
  //   ],
  //   image: "/work/Warehouse.png",
  // },
  // {
  //   id: 6,
  //   title: "E-commerce Platform",
  //   description:
  //     "Developing an E-learning platform tailored for students to easily purchase courses, monitor their progress, and for teachers to effortlessly upload new courses and manage course details. Our platform prioritizes user-friendliness and efficiency, ensuring a seamless experience for both students and educators.",
  //   category: "Full stack development",
  //   year: "2024",
  //   client: "Personal Project",
  //   blackground: "bg-yellow-500",
  //   frameWork: [
  //     "Next.js",
  //     "Prisma",
  //     "TailwindCSS",
  //     "Electron.js",
  //     "Express.js",
  //   ],
  //   image: "/work/Warehouse.png",
  // },
  {
    id: 7,
    title: "Iphone 15 Pro Max Website",
    description:
      "redesigning the website for the new Iphone 15 Pro Max, focusing on a modern and sleek design to showcase the phone's features and specifications. The website is designed to be user-friendly and visually appealing, ensuring a seamless user experience for potential customers.",
    category: "Front-end development",
    year: "2024",
    client: "Personal Project",
    blackground: "bg-yellow-500",
    frameWork: ["React", "TailwindCSS", "Three.js", "GSAP"],
    image: "/work/iphone.png",
  },
];
